export enum Role {
  // Platform Level
  PLATFORM_SUPER_ADMIN = "PLATFORM_SUPER_ADMIN",

  // Company Level
  COMPANY_ADMIN = "COMPANY_ADMIN",
  HR = "HR",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  ACCOUNTANT = "ACCOUNTANT",
  SALES_MANAGER = "SALES_MANAGER",
  SALES_EXECUTIVE = "SALES_EXECUTIVE",
  INVENTORY_MANAGER = "INVENTORY_MANAGER",
  PROJECT_ENGINEER = "PROJECT_ENGINEER",
  CONTRACTOR = "CONTRACTOR",
  WORKER = "WORKER",
}
